/**
 * Generates seed.sql with real bcrypt hashes.
 * Run: node generate_seed.js
 * Then: psql -U esnsa_user -d esnsa_db -f seed.sql
 */
require('dotenv').config({ path: '../.env' });
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');

const SALT_ROUNDS = 10;

const users = [
  { officer_id: 'DIR001', name: 'Director, Energy Security',  role: 'DIRECTOR', clearance: 'TOP SECRET',   password: 'onsa2026'  },
  { officer_id: 'ANL002', name: 'Sr. Intelligence Analyst',   role: 'ANALYST',  clearance: 'SECRET',       password: 'analyst'   },
  { officer_id: 'OPS003', name: 'Operations Officer',          role: 'OFFICER',  clearance: 'CONFIDENTIAL', password: 'ops123'    },
  { officer_id: 'ADM000', name: 'System Administrator',        role: 'ADMIN',    clearance: 'SYSTEM',       password: 'admin123'  },
];

async function generateSeed() {
  console.log('[generate_seed] Hashing passwords...');

  const userInserts = await Promise.all(users.map(async (u) => {
    const hash = await bcrypt.hash(u.password, SALT_ROUNDS);
    return `('${u.officer_id}', '${u.name}', '${u.role}', '${u.clearance}', '${hash}')`;
  }));

  const sql = `-- ─────────────────────────────────────────────────────────────────────
-- ESNSA Seed Data  (auto-generated by generate_seed.js)
-- ─────────────────────────────────────────────────────────────────────

-- ─── USERS ──────────────────────────────────────────────────────────
INSERT INTO users (officer_id, name, role, clearance, password_hash) VALUES
${userInserts.join(',\n')}
ON CONFLICT (officer_id) DO NOTHING;

-- ─── STAKEHOLDERS ───────────────────────────────────────────────────
INSERT INTO stakeholders (name, role, status) VALUES
('NNPC Limited',         'National Oil Company',            'ACTIVE'),
('Nigerian Navy (NNS)',  'Maritime Security Command',       'ACTIVE'),
('Op Delta Safe',        'Army Niger Delta Command',        'ACTIVE'),
('DSS / SSS',            'Domestic Intelligence Service',   'ACTIVE'),
('Shell SPDC',           'IOC / Infrastructure Owner',      'STANDBY'),
('NSCDC',                'Civil Defence / Pipeline Guard',  'ACTIVE'),
('NIA',                  'National Intelligence Agency',    'ACTIVE'),
('Rivers State Govt',    'State Security Liaison',          'STANDBY'),
('NIMASA',               'Maritime Administration',         'ACTIVE'),
('EFCC',                 'Economic Crimes Commission',      'STANDBY'),
('NPF',                  'Nigeria Police Force',            'ACTIVE'),
('NUPRC',                'Upstream Petroleum Regulator',    'ACTIVE')
ON CONFLICT (name) DO NOTHING;

-- ─── DEMO THREATS ───────────────────────────────────────────────────
INSERT INTO threats (incident_id, type, location, state, latitude, longitude, severity, status, loss_estimate, description) VALUES
('T-001','Pipeline Breach',     'Bonny-Forcados Corridor',        'Rivers',  4.9,  6.1,  'CRITICAL','ACTIVE',     '12,400 bbl/day',       'Major breach detected on Bonny-Forcados export line KP-88. Flow reduced to 34% capacity.'),
('T-002','Illegal Refinery',    'Abia State Hinterland',          'Abia',    5.5,  7.5,  'HIGH',    'CONTAINED',  '~3,200 bbl/day',       'Network of 3 illegal refineries discovered. Army/NSCDC operation ongoing.'),
('T-003','Maritime Intrusion',  'OML 58 Offshore Block',          'Offshore',3.8,  5.2,  'HIGH',    'MONITORING', 'Unquantified',         'Unidentified vessels with irregular AIS signatures detected near OML 58.'),
('T-004','Pipeline Vandalism',  'Warri–Kaduna Trunk Line',        'Delta',   5.5,  5.7,  'MEDIUM',  'RESOLVED',   '~800 bbl',             'Vandalism at KP-22. Repaired within 4 hours. NSCDC patrol increased.'),
('T-005','Militant Threat',     'Maiduguri Gas Pipeline Corridor','Borno',  11.8, 13.1,  'HIGH',    'MONITORING', 'Preemptive',           'NIA HUMINT: planned sabotage of gas pipeline in 48-72hr window. Verification ongoing.'),
('T-006','Gas Pipeline Sabotage','NLNG Boni Corridor',            'Rivers',  4.7,  7.0,  'CRITICAL','ACTIVE',     'Gas supply disrupted', 'Sabotage of NLNG gas feed pipeline. Estimated 18% reduction in LNG export capacity.')
ON CONFLICT (incident_id) DO NOTHING;

-- ─── DEMO INTEL ITEMS ───────────────────────────────────────────────
INSERT INTO intel_items (classification, source, content) VALUES
('SECRET',       'NIA SIGINT',  'Intercept suggests armed group mobilizing near Nembe Creek waterway. Coordinates forwarded to NNS FOB.'),
('RESTRICTED',   'NNPCL OPS',  'Flow rate on Trans Niger Pipeline restored to 78% after emergency valve repair at KP-44.'),
('CONFIDENTIAL', 'DSS FIELD',  'Community leader in Gbaramatu Kingdom reports unknown vessels sighted at 03:00 hrs. Photos attached.'),
('RESTRICTED',   'ARMY J2',    'Op Delta Safe patrol: 3 illegal refineries deactivated, 7 suspects arrested, 240 drums crude oil seized.'),
('CONFIDENTIAL', 'NIMASA',     'Vessel EVER FAST flagged for irregular AIS transponder activity near OML 58. Coast Guard alerted.'),
('SECRET',       'NIA HUMINT', 'Source reports planned sabotage of Maiduguri gas pipeline in 48-72 hrs. Verification ongoing. Army notified.'),
('RESTRICTED',   'NNPCL OPS',  'Production output 1.67M bpd vs 2.06M bpd budget target. Deficit attributed to T-006 and T-001 incidents.');
`;

  const outPath = path.join(__dirname, 'seed.sql');
  fs.writeFileSync(outPath, sql, 'utf8');
  console.log(`[generate_seed] ✅ Written to ${outPath}`);
}

generateSeed().catch(console.error);
